export PATH=~/.bin:$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH
export ZSH=$HOME/.oh-my-zsh
export LANG=en_US.UTF-8

ZSH_THEME="lavcraft"
# ZSH_TMUX_ITERM2=true
ZSH_TMUX_AUTOSTART=true
plugins=(tmux git ssh-agent)

# zstyle :omz:plugins:ssh-agent agent-forwarding on
zstyle :omz:plugins:ssh-agent identities github gitlab jrg_mc
zstyle :omz:plugins:ssh-agent lifetime 36h

source $ZSH/oh-my-zsh.sh

# export LANG=en_US.UTF-8


# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"
source ~/.bash_profile
source ~/.scripts
source ~/.scripts.tmux
source ~/.aliases
source ~/.keyrebinder
source ~/.fzf.completion.zsh
source ~/.fzf.bindings.zsh

# Configure NVM
export NVM_DIR=~/.nvm
source /usr/local/opt/nvm/nvm.sh

# Configure kubernetes tools
source <(kubectl completion zsh)
source <(bash completion zsh)
source <(argo completion zsh)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Init SDKMAN if possible
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# added by travis gem
[ -f ~/.travis/travis.sh ] && source ~/.travis/travis.sh

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi


# The next line updates PATH for Yandex Cloud CLI.
source "/usr/local/Caskroom/yandex-cloud-cli/latest/yandex-cloud-cli/completion.zsh.inc"
