export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH=$HOME/.oh-my-zsh
export LANG=en_US.UTF-8

ZSH_THEME="robbyrussell"
plugins=(tmux git ssh-agent)

# zstyle :omz:plugins:ssh-agent agent-forwarding on
zstyle :omz:plugins:ssh-agent identities id_rsa github c_gitlab c_servers_dev c_bitbucket
zstyle :omz:plugins:ssh-agent lifetime 36h

source $ZSH/oh-my-zsh.sh

# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

export PATH=~/.bin:$PATH
source ~/.bash_profile
source ~/.scripts
source ~/.scripts.tmux
source ~/.aliases
source ~/.keyrebinder
source ~/.fzf.completion.zsh
source ~/.fzf.bindings.zsh

# Configure NVM
export NVM_DIR=~/.nvm
source /usr/local/opt/nvm/nvm.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Init SDKMAN if possible
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# Run TMUX
# if [ -z "$TMUX" ]
# then
#     tmux attach -t TMUX || tmux new -s TMUX
# fi

